jobs:
  - job: "Web_Release"
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: Bash@3
        displayName: 'Pull latest from branch'
        inputs:
          targetType: filePath
          filePath: './scripts/git-pull-current-branch.sh'
        env:
          SOURCE_BRANCH: $(Build.SourceBranch)

      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: custom
          workingDir: .
          verbose: false
          customCommand: ci

      - task: Bash@3
        displayName: 'Create artifact'
        inputs:
          targetType: filePath
          filePath: './scripts/generate-web-artifact.sh'

      - task: AzureFileCopy@3
        displayName: 'AzureBlob File Copy to $DEV_STORAGE_ACCOUNT'
        inputs:
          SourcePath: './build'
          azureSubscription: $(azureSubscription)
          destination: azureBlob
          storage: $(DEV_STORAGE_ACCOUNT)
          containerName: '$web'
        # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

      - task: AzureFileCopy@3
        displayName: 'AzureBlob File Copy to $PROD_STORAGE_ACCOUNT'
        inputs:
          SourcePath: './build'
          azureSubscription: $(azureSubscription)
          destination: azureBlob
          storage: $(PROD_STORAGE_ACCOUNT)
          containerName: '$web'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

      - bash: |
          echo
          echo "Head to $DEV_URL"
        displayName: "Web URL"
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

      - bash: |
          echo
          echo "Head to $PROD_URL"
        displayName: "Web URL"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
