parameters:
  GitHubConnection: '' # defaults for any parameters that aren't specified
  repositoryName: ''
  isPreRelease: true
  isDraft: false
  lastReleaseTag: ''

jobs:
  - template: build-artifact.yml
    parameters:
      name: LinuxArtifact
      pool:
        vmImage: ubuntu-16.04
      os: linux
      artifact: vott*.snap

  - template: build-artifact.yml
    parameters:
      name: WindowsArtifact
      pool:
        vmImage: "windows-2019"
      os: windows
      artifact: vott*.exe

  - template: build-artifact.yml
    parameters:
      name: MacOSArtifact
      pool:
        vmImage: macOS-10.15
      os: mac
      artifact: vott*.dmg

  - job: Create_Github_Release
    timeoutInMinutes: 30 # timeout on job if deploy is not completed in 30 minutes
    dependsOn:
      - LinuxArtifact
      - WindowsArtifact
      - MacOSArtifact

    pool:
      vmImage: ubuntu-16.04

    steps:
    - template: git-pull-current-branch.yml

    - download: current

    - task: GitHubRelease@1
      displayName: 'GitHub release (create)'
      inputs:
        gitHubConnection: ${{ parameters.GitHubConnection }}
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        releaseNotesFilePath: './CHANGELOG.md'
        assets: |
          ../linux/*
          ../windows/*
          ../mac/*
        isDraft: ${{ parameters.isDraft }}
        isPreRelease: ${{ parameters.isPrelease }}
        changeLogCompareToRelease: 'lastNonDraftReleaseByTag'
        changeLogCompareToReleaseTag: ${{ parameters.lastReleaseTag }}
        changeLogType: 'commitBased'
