name: "Web Release [$SourceBranchName] - $(Date:yyyyMMdd)$(Rev:.r)"
trigger:
  branches:
    include:
      - develop
      - master
pr: none # disable CI build for PR

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: "pj-little-sub"
  DEV_STORAGE_ACCOUNT: 'vottv2'
  PROD_STORAGE_ACCOUNT: 'vott'

steps:
  - template: templates/generate-web-artifact.yml

  - task: AzureFileCopy@3
    displayName: 'AzureBlob File Copy to $DEV_STORAGE_ACCOUNT'
    inputs:
      SourcePath: './build'
      azureSubscription: $(azureSubscription)
      destination: azureBlob
      storage: $(DEV_STORAGE_ACCOUNT)
      containerName: '$web'
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

  - task: AzureFileCopy@3
    displayName: 'AzureBlob File Copy to $PROD_STORAGE_ACCOUNT'
    inputs:
      SourcePath: './build'
      azureSubscription: $(azureSubscription)
      destination: azureBlob
      storage: $(PROD_STORAGE_ACCOUNT)
      containerName: '$web'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
